version: '3.7'

services:
  smabackend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=sma_rest.settings.local
      -
    volumes:
      - media:/srv/appdata/media
      - static:/srv/appdata/static
      - sqlite_dir:/srv/appdata/sqlite
    ports:
      - 8000:8000 # host:container
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - smabackend
volumes:
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/bayerl/projects/sma_rest/mounts/media
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/bayerl/projects/sma_rest/mounts/static
  sqlite_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/bayerl/projects/sma_rest/mounts/sqlite
